---
title: "ADA Class Project"
author: "Bernadette King"
date: "2025-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#loading packages and data 
pacman::p_load(readr, tidyverse, nnet, MASS, funModeling, brant, broom, odds.n.ends, haven)

brfss <- read_xpt("/Users/bernadetteking/Downloads/LLCP2024.XPT " )
```

```{r}
#Filtering my data to include only states that asked the questions for emotional support being met and caregiver questions. The numbers represent the states with both questions. 

list1 <- c(8,9,10,17,20,21,22,26,28,32,33,36,37,39,40,41,46,48,49,51,55,56)

list2 <- c(1,2,4,5,6,10,11,13,15,16,18,19,22,24,25,27,28,30,31,33,34,
           35,37,38,39,72,44,45,46,49,50,78,54,55)
common_states <- intersect(list1, list2)
common_states


brfss_filtered <- brfss %>%
  filter(`_STATE` %in% common_states)

View (brfss_filtered)

```

```{r}
#filter only necessary columns 

brfss3<- brfss_filtered[, c("_STATE", "_AGE80", "INCOME3", "SEXVAR","_IMPRACE", "CAREGIV1", "EMTSUPRT" )]
View(brfss3)

brfss3$INCOME3[brfss3$INCOME3 %in% c(77, 99)] <- NA

```

```{r}

library(mice)

#recoding INCOME3 for imputation
brfss3$INCOME3 <- factor(brfss3$INCOME3,
                         levels = c(1,2,3,4,5,6,7,8,9,10,11),
                         labels = c("Less than $10k",
                                    "$10k–15k",
                                    "$15k–20k",
                                    "$20k–25k",
                                    "$25k–35k",
                                    "$35k–50k",
                                    "$50k–75k",
                                    "$75k-100k",
                                    "$100k-150k",
                                    "$150-200k",
                                       "200k+"))

#recoding CAREGIV1 for imputation
brfss3$CAREGIV1[brfss3$CAREGIV1 %in% c(7,9)] <- NA
brfss3$CAREGIV1 <- ifelse(brfss3$CAREGIV1 == 1, 1,
                          ifelse(brfss3$CAREGIV1 == 2, 0, NA))
brfss3$CAREGIV1 <- factor(brfss3$CAREGIV1, levels = c(0,1))

#Recoding EMTSUPRT for imputation
brfss3$EMTSUPRT[brfss3$EMTSUPRT %in% c(7,9)] <- NA
brfss3$EMTSUPRT <- factor(brfss3$EMTSUPRT)

#recoding _IMPRACE for imputation
brfss3$
#running imputation
imp_brfss3 <- mice(brfss3,
                   m = 10,
                   maxit = 5,
                   seed = 1000000)

#looking at imputed dataset
completed_brfss <- complete(imp_brfss3, action = "long") 

View(completed_brfss)

saveRDS(completed_brfss, file = "completed_brfss.rds")

```

```{r}
library(dplyr)

#recoding emotional support to a binary variable. If 1 or 2 ("always" or "usually" responses) recoded to 1 to signify yes, everything else is coded to 0 to signify no.  
brfss4 <- completed_brfss %>%
  mutate(EMTSUPRT2 = ifelse(EMTSUPRT %in% c(1,2), 1, 0))
View(brfss4)
```


#Now to check assumptions and run the model
```{r}
pacman::p_load(odds.n.ends, blorr, lmtest, car, broom, tidyverse, readr, jtools) 

#Making sure we have enough cases. Cases are those who do not have emotional support met (0), and who are a caregiver (1). There are 40,335 cases. 
table( brfss4$CAREGIV1, brfss4$EMTSUPRT2)


```

```{r}
#Running univariate GLM
model1<- glm(EMTSUPRT2 ~ CAREGIV1, data=brfss4, family="binomial")
summary(model1) # get log results

#Running this in place of odds.n.ends as the code would not run properly. This gives ORs and CIs.
exp(cbind(OR = coef(model1), confint.default(model1)))

#do not need to test linearity as the predictor variable is binary. 
```

```{r}


#checking for effect modification of sex

model_reduced <- glm(EMTSUPRT2 ~ CAREGIV1 + `_AGE80`+ INCOME3 + `_IMPRACE`+ SEXVAR, 
                     data = brfss4, family = binomial)

model_full <- glm(EMTSUPRT2 ~ CAREGIV1 + `_AGE80`+ INCOME3 + `_IMPRACE`+ SEXVAR*CAREGIV1, 
                     data = brfss4, family = binomial)
lrtest(model_reduced, model_full)

#sex is an effect modifier as the interaction term significantly improves model fit. 

#Controlling for income, age and race. Adding sex as an effect modifier. 


model2<- glm(EMTSUPRT2 ~ CAREGIV1+ `_AGE80`+ INCOME3 + `_IMPRACE` + SEXVAR*CAREGIV1, data=brfss4, family="binomial")
summary(model2)

exp(cbind(
  OR = coef(model2),
  confint(model2)
))


```

```{r}
#Checking for multicollinearity
library(car)
summ(model2, vifs = TRUE)

#values are all close to 1. No multicollinearity
```

```{r}
#checking for influential cases with Cook's distance

#plotting Cook's distance
plot(model2, which = 4, id.n = 3, col="red")

#Cook's Distance Calculations 
model2.data <- augment(model2) %>%  
  mutate(index = 1:n()) 

head(model2.data)

#Identifying and excluding influential cases
cuttoff <- 1 # defines cutoff variable (1 is a common threshold)


brfss_in <- model2.data %>% # excludes observations
  filter(.cooksd < cuttoff)

nrow(brfss_in)/nrow(brfss4)

#No influential cases identified
```

```{r}
#checking model fit

blr_model_fit_stats(model2)

blr_test_hosmer_lemeshow(model2)

#HL is significant-likely because of the large sample size. 
```

```{r}
#Running a calibration plot to ensure good fit of the model, despite the significant HL. 

# predicted probabilities
brfss4$pred <- predict(model2, newdata = brfss4, type = "response")

# deciles of predicted risk
dec <- cut(brfss4$pred,
           quantile(brfss4$pred, seq(0,1,0.1), na.rm=TRUE),
           include.lowest = TRUE)

# observed vs expected
obs <- tapply(brfss4$EMTSUPRT2, dec, mean, na.rm=TRUE)
exp <- tapply(brfss4$pred,      dec, mean, na.rm=TRUE)

# calibration plot
plot(exp, obs, pch=19,
     xlab="Predicted probability",
     ylab="Observed probability",
     main="Calibration Plot")
abline(0,1,col="red",lwd=2)

#The calibration plot looks like a good fit. 
```

```{r}
#Testing to see if including the confounders improves model fit. 
lrtest(model2, model1)

#The results show a significant difference, thus model 2 is a better fitting model. 
```

```{r}
library(table1)
table1(~`_AGE80` + `_IMPRACE`+ INCOME3 + CAREGIV1 +EMTSUPRT2|SEXVAR, brfss4 )
```

```{r}
brfss_male   <- subset(brfss4, SEXVAR == 1)
brfss_female <- subset(brfss4, SEXVAR == 2)


library(broom)

get_or <- function(model, varname, ref_label="1.0 (ref.)") {

  tbl <- tidy(model, exponentiate = TRUE, conf.int = TRUE)

  # filter rows for the variable of interest
  rows <- tbl[grepl(varname, tbl$term), ]

  # format OR (CI)
  formatted <- paste0(
    round(rows$estimate, 2), 
    " (", 
    round(rows$conf.low, 2), 
    "–", 
    round(rows$conf.high, 2), 
    ")"
  )

  # prepend reference row
  final <- c(ref_label, formatted)
  names(final) <- NULL

  return(final)
}

mod_male_crude <- glm(EMTSUPRT2 ~ CAREGIV1,
                      data = brfss_male, family = binomial)

mod_male_adj <- glm(
  EMTSUPRT2 ~ CAREGIV1 + `_AGE80` + INCOME3 + `_IMPRACE`,
  data = brfss_male, family = binomial
)

mod_female_crude <- glm(EMTSUPRT2 ~ CAREGIV1,
                        data = brfss_female, family = binomial)

mod_female_adj <- glm(
  EMTSUPRT2 ~ CAREGIV1 + `_AGE80` + INCOME3 + `_IMPRACE`,
  data = brfss_female, family = binomial
)

# extract ORs for CAREGIV1
overall_unadj <- get_or(model1, "CAREGIV1")
overall_adj   <- get_or(model2,   "CAREGIV1")

male_unadj    <- get_or(mod_male_crude,    "CAREGIV1")
male_adj      <- get_or(mod_male_adj,      "CAREGIV1")

female_unadj  <- get_or(mod_female_crude,  "CAREGIV1")
female_adj    <- get_or(mod_female_adj,    "CAREGIV1")

# assemble into a table
table_out <- data.frame(
  Level = c("No", "Yes"),
  Overall_Unadj  = model1,
  Overall_Adj    = model2,
  Male_Unadj     = male_unadj,
  Male_Adj       = male_adj,
  Female_Unadj   = female_unadj,
  Female_Adj     = female_adj
)

table_out


```

```{r}
get_or <- function(model){
  est <- coef(model)
  se  <- sqrt(diag(vcov(model)))
  or  <- exp(est)
  ci_l <- exp(est - 1.96*se)
  ci_u <- exp(est + 1.96*se)

  data.frame(
    term = names(est),
    OR = round(or, 2),
    CI = paste0("(", round(ci_l, 2), "–", round(ci_u, 2), ")"),
    stringsAsFactors = FALSE
  )
}
# Overall
m_unadj_all <- glm(EMTSUPRT2 ~ CAREGIV1, data = brfss4, family="binomial")
m_adj_all <- glm(EMTSUPRT2 ~ CAREGIV1 + `_AGE80` + INCOME3 + `_IMPRACE` + SEXVAR*CAREGIV1,
                 data = brfss4, family="binomial")

# Males only
m_unadj_male <- glm(EMTSUPRT2 ~ CAREGIV1, 
                    data = subset(brfss4, SEXVAR == 1),
                    family="binomial")
m_adj_male <- glm(EMTSUPRT2 ~ CAREGIV1 + `_AGE80` + INCOME3 + `_IMPRACE`, 
                  data = subset(brfss4, SEXVAR == 1),
                  family="binomial")

# Females only
m_unadj_fem <- glm(EMTSUPRT2 ~ CAREGIV1, 
                   data = subset(brfss4, SEXVAR == 2),
                   family="binomial")
m_adj_fem <- glm(EMTSUPRT2 ~ CAREGIV1 + `_AGE80` + INCOME3 + `_IMPRACE`, 
                 data = subset(brfss4, SEXVAR == 2),
                 family="binomial")
tab_all_u <- get_or(m_unadj_all)
tab_all_a <- get_or(m_adj_all)

tab_male_u <- get_or(m_unadj_male)
tab_male_a <- get_or(m_adj_male)

tab_fem_u <- get_or(m_unadj_fem)
tab_fem_a <- get_or(m_adj_fem)
get_caregiver_row <- function(unadj, adj){
  # Find CAREGIV1Yes or CAREGIV11 or whatever your level name is
  caregiver_term <- grep("CAREGIV1", unadj$term, value = TRUE)
  
  data.frame(
    Category = c("No (ref)", "Yes"),
    Unadj = c("1.00", paste0(unadj$OR[unadj$term==caregiver_term], " ", unadj$CI[unadj$term==caregiver_term])),
    Adj   = c("1.00", paste0(adj$OR[adj$term==caregiver_term], " ", adj$CI[adj$term==caregiver_term]))
  )
}
overall_tbl <- get_caregiver_row(tab_all_u, tab_all_a)
male_tbl    <- get_caregiver_row(tab_male_u, tab_male_a)
fem_tbl     <- get_caregiver_row(tab_fem_u, tab_fem_a)

final_table <- data.frame(
  Category = overall_tbl$Category,
  
  Overall_Unadj = overall_tbl$Unadj,
  Overall_Adj   = overall_tbl$Adj,
  
  Male_Unadj = male_tbl$Unadj,
  Male_Adj   = male_tbl$Adj,
  
  Female_Unadj = fem_tbl$Unadj,
  Female_Adj   = fem_tbl$Adj
)

install.packages("flextable")
library(flextable)

ft <- flextable(final_table)

ft <- set_header_labels(
  Category       = "Caregiver\n(Exposure)",
  Overall_Unadj  = "Overall\nUnadjusted OR (95% CI)",
  Overall_Adj    = "Overall\nAdjustedᵃ OR (95% CI)",
  Male_Unadj     = "Males\nUnadjusted OR (95% CI)",
  Male_Adj       = "Males\nAdjustedᵇ OR (95% CI)",
  Female_Unadj   = "Females\nUnadjusted OR (95% CI)",
  Female_Adj     = "Females\nAdjustedᵇ OR (95% CI)"
)




```